### ISSUE TITLE
Blocking animations

### ISSUE THREAD

**Issue by Jin-Jiyunsun** [geheur/weapon-animation-replacer#19] opened 2022-01-08 16:47 UTC
As far as I can tell these can't be changed with the plugin yet, there's only a few of them I think but there's a couple unique ones, blocking with a shield is different than a defender for example, as is blocking while unarmed.

Exmaple would be hiding a shield in offhand and your character still pretending to block with a shield when there visually nothing there

**Comment by geheur** [comment] 2022-01-09 02:40
Duplicate of #4.

**Closed by geheur** 2022-01-09 02:40 UTC
