### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by sazoo93** [geheur/weapon-animation-replacer#45] opened 2023-10-23 01:17 UTC
Ive been trying to use your plugin but for some reason its not showing up on the right side in order to replace the transmogs and stuff. I tried to uninstall and reinstall the app but its still showing that is installed and not showing up. 
![image](https://github.com/geheur/weapon-animation-replacer/assets/148730944/22f1281d-730b-4324-8785-84709643811c)

**Comment by sazoo93** [comment] 2023-10-23 01:18
I turned it off and on and still not working for me. Im not sure if the files are corrupted or isnt working properly.

**Comment by geheur** [comment] 2023-10-23 01:53
can you send me your `client.log` from `.runelite/logs` and the line that starts with `WeaponAnimationReplacer.transmogSets` in your profile in `.runelite/profiles2`?

And if you delete that line (after closing every runelite client you have open) it will probably fix it.

**Comment by sazoo93** [comment] 2023-10-23 05:49
[client.log](https://github.com/geheur/weapon-animation-replacer/files/13066493/client.log)

**Comment by sazoo93** [comment] 2023-10-23 05:50
Im not able to find WeaponAnimationReplacer.transmogSets on my profile 2

**Comment by geheur** [comment] 2023-10-23 08:14
Someone else sent me their stuff, and I know what the issue is for them. it's likely the same for you. I'll try and get a fix out soon.

It can be manually fixed if you remove the `,{"name"\:"","enabled"\:true,"minimized"\:false}` from the save data btw.

**Comment by sazoo93** [comment] 2023-10-23 11:30
Thanks, would you be able to tell me where do I find this? ,{"name"\:"","enabled"\:true,"minimized"\:false}

**Comment by sazoo93** [comment] 2023-10-23 11:36
Ill wait for you to fix it :)! thanks so much for the support

**Comment by geheur** [comment] 2023-10-23 11:40
it's in the line with `WeaponAnimationReplacer.transmogSets`. but hopefully it will be fixed in a few hours if I'm lucky.

**Comment by geheur** [comment] 2023-10-25 07:56
This has been fixed in 3.5.1.

**Closed by geheur** 2023-10-25 07:56 UTC
