### ISSUE TITLE
Scythe swing doesn't trigger if there is no attack animation override.

### ISSUE THREAD

**Issue by GrimWrath** [geheur/weapon-animation-replacer#24] opened 2022-04-17 14:42 UTC
When attempting to use the effect SCYTHE_SWING and changing the color, nothing is produced, no default nor changed animation.
![OpenOSRS_kZnfD63bTX](https://user-images.githubusercontent.com/4154791/163719485-ed01f0b1-99af-4453-99a9-7d7ed7611499.png)
![OpenOSRS_yzW9eSqrgZ](https://user-images.githubusercontent.com/4154791/163719486-0a8acc82-e3e3-44dc-b6e5-29f682d73441.png)

**Comment by geheur** [comment] 2022-04-17 18:20
What weapon are you using (the real one, not the transmog). The plugin uses a list of animations to determine when you are attacking so that it can make the scythe swing trail. If you're using a weapon with unique animations that I haven't added, that would explain this.

**Comment by GrimWrath** [comment] 2022-04-17 18:54
I tried using my own sanguine scythe as well as my bare fists.

**Comment by geheur** [comment] 2022-04-17 19:43
Ah I see, this is a bug. If you don't override the attack animation it misses the code path that triggers the swing trail. So as a temporary fix you could add the scythe (or any other animation set) animations override.

Also fwiw the plugin currently does not remove the existing scythe's swing trail. I don't have a scythe so this got overlooked ;) So if you are using this with your real scythe it may not work as expected.

**Comment by GrimWrath** [comment] 2022-04-17 19:50
I see - thank you. feel free to reach out to me ingame at Grim Fervor and I could help you out with ids and things you may need for those out of reach weapons/armor :)

**Comment by GrimWrath** [comment] 2022-04-17 19:57
It seems I'm having the same issue following your instructions. Are you able to reproduce a change in scythe swing color?
![image](https://user-images.githubusercontent.com/4154791/163730250-8e454d4e-f9ae-4815-87da-4c2cdd3efd2d.png)

**Comment by geheur** [comment] 2022-04-20 07:59
For anyone else reading this, this issue (as well as pose animation overrides probably not working) can also be caused by not using runelite. But I think that will be fixed soon.

**Comment by geheur** [comment] 2023-03-24 07:18
I fixed this a while ago, and openosrs no longer exists afaik. so either way this issue is fixed.

**Closed by geheur** 2023-03-24 07:18 UTC
Labels: bug
